# Generated by Django 4.2 on 2023-07-20 05:20

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_carousel_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='portfolio_desktop_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Hover/Portfolio Carousel Desktop Image', null=True, upload_to='Carousel/portfolio/pics', verbose_name='Portfolio Carousel Item Desktop Image'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='portfolio_mobile_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Hover/Portfolio Carousel Mobile Image', null=True, upload_to='Carousel/portfolio/pics', verbose_name='Portfolio Carousel Item Mobile Image'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='desktop_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Hover/Carousel Desktop Image', null=True, upload_to='Carousel/pics', verbose_name='Carousel Item Desktop Image'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='mobile_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Hover/Carousel Mobile Image', null=True, upload_to='Carousel/pics', verbose_name='Carousel Item Mobile Image'),
        ),
    ]
