# Generated by Django 4.2 on 2023-07-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_carousel_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Provide Brand Name', max_length=100, null=True),
        ),
    ]
