# Generated by Django 4.2 on 2023-06-29 11:10

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='The Name of the Service', max_length=200)),
                ('featured_image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Service Background Image', null=True, upload_to='Service/featured-images')),
                ('mobile_image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Mobile Image for hover image or carousel image', null=True, upload_to='Gallery/mobile_images')),
                ('desktop_image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Desktop Image for hover image or carousel image', null=True, upload_to='Gallery/desktop_images')),
                ('icon_image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Service Icon Image', null=True, upload_to='Service/icon-images')),
                ('description', models.TextField(blank=True, help_text='Service Description', max_length=1000, null=True)),
                ('sort_order', models.PositiveIntegerField(help_text='Sort order to list the services', unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
    ]
