# Generated by Django 4.2 on 2023-06-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='The Blog Title', max_length=100, unique=True),
        ),
    ]
