# Generated by Django 4.2 on 2023-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_popular_blog',
            field=models.BooleanField(default=False, help_text='Popular Blog?'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured Blog?'),
        ),
    ]
