# Generated by Django 4.2 on 2023-07-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_is_popular_blog_alter_blog_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_description',
            field=models.TextField(blank=True, help_text='Blog Sub Description', max_length=300, null=True),
        ),
    ]
