# Generated by Django 4.2 on 2023-08-02 18:35

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_sub_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True, verbose_name='Blog Content'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, help_text="Blog's Meta Description", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, help_text="Blog's Meta Title", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(help_text='Blog Content This field is deprecated', max_length=10000),
        ),
    ]
