# Generated by Django 4.2 on 2023-06-29 11:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, help_text='The nearby landmark', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='City Name', max_length=50, null=True)),
                ('state', models.CharField(blank=True, help_text='State Name', max_length=50, null=True)),
                ('country', models.CharField(blank=True, help_text='Country Name', max_length=50, null=True)),
                ('pincode', models.PositiveIntegerField(blank=True, help_text='Address Pincode', null=True)),
                ('mobile', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True), blank=True, default=list, help_text='Mobile number', null=True, size=None)),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, help_text='Email Address', size=None)),
                ('is_active', models.BooleanField(default=True, help_text='Status')),
                ('is_default', models.BooleanField(default=False, help_text='Used For Default Address')),
                ('full_address', models.TextField(blank=True, help_text='Represents Full Address', max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Address',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text="Enquiry person's first name", max_length=40)),
                ('last_name', models.CharField(help_text="Enquiry person's last name", max_length=40)),
                ('email', models.EmailField(help_text="Enquiry person's email", max_length=255)),
                ('phone_number', models.CharField(help_text="Enquiry person's mobile number", max_length=10)),
                ('message', models.TextField(blank=True, help_text='Appointment Booking Message', max_length=1000, null=True)),
                ('service', models.ForeignKey(help_text='Appointment Booking Service', on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'verbose_name_plural': 'Enquiries (Contact Us)',
            },
        ),
    ]
