# Generated by Django 4.2 on 2023-07-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactenquiry_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('GENERAL_ENQUIRY', 'GENERAL ENQUIRY'), ('OVERALL_PACKAGE', 'OVERALL PACKAGE'), ('BRAND_PARTNERS', 'BRAND PARTNERS'), ('OTHERS', 'OTHERS')], default=1, help_text='The Enquiry Type', max_length=50),
            preserve_default=False,
        ),
    ]
