# Generated by Django 4.2 on 2023-07-01 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('carousel', '0001_initial'),
        ('contact_us', '0003_contactenquiry_enquiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='The service enquiring about', null=True, on_delete=django.db.models.deletion.SET_NULL, to='carousel.carousel'),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='service',
            field=models.ForeignKey(blank=True, help_text='The service enquiring about', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service'),
        ),
    ]
