# Generated by Django 4.2 on 2023-06-29 11:10

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_type', models.CharField(blank=True, choices=[('CLIENT_GALLERY', 'CLIENT GALLERY'), ('BRIDAL_SERVICE_GALLERY', 'BRIDAL SERVICE GALLERY')], help_text='The gallery depends on type', max_length=100, null=True)),
                ('name', models.CharField(blank=True, help_text='The name', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='The description of the Item', max_length=1000, null=True)),
                ('featured_image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Background Image', null=True, upload_to='Gallery/pics')),
                ('mobile_image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Upload Image for Mobile', null=True, upload_to='Gallery/mobile_images')),
                ('desktop_image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Upload Image for Desktop', null=True, upload_to='Gallery/desktop_images')),
                ('hosted_video', models.FileField(blank=True, help_text='Video upload file', max_length=200, null=True, upload_to='Gallery/videos')),
                ('provider', models.CharField(blank=True, choices=[('YOUTUBE', 'YOUTUBE'), ('FACEBOOK', 'FACEBOOK'), ('INSTAGRAM', 'INSTAGRAM'), ('VIMEO', 'VIMEO')], help_text='Video provider name', max_length=100, null=True)),
                ('provider_url', models.URLField(blank=True, help_text='Video URL', max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Mobile Image for hover image or carousel image', null=True, upload_to='Gallery/mobile_images')),
                ('desktop_image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Desktop Image for hover image or carousel image', null=True, upload_to='Gallery/desktop_images')),
                ('hosted_video', models.FileField(blank=True, help_text='Video upload file', max_length=200, null=True, upload_to='Gallery/videos')),
                ('provider', models.CharField(blank=True, choices=[('YOUTUBE', 'YOUTUBE'), ('FACEBOOK', 'FACEBOOK'), ('INSTAGRAM', 'INSTAGRAM'), ('VIMEO', 'VIMEO')], help_text='Video provider name', max_length=100, null=True)),
                ('provider_url', models.URLField(blank=True, help_text='Video URL', max_length=300, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='gallery.gallery')),
            ],
            options={
                'verbose_name_plural': 'Gallery Items',
                'ordering': ('-id',),
            },
        ),
    ]
