import graphene


class CarouselFilterEnum(graphene.Enum):
    """
    The Carousel Enum defines the Carousel Types
    """
    _90_DAYS_JOURNEY = "90 DAYS JOURNEY"
    MAGICAL_MAKEOVER = "MAGICAL MAKEOVER"
    SERVICES_BANNER = "SERVICES BANNER"
    MAKEUP_VARIATIONS = "MAKEUP VARIATIONS"
    TOP_MAKEUP_ARTISTS = "TOP MAKEUP ARTISTS"
    SPECIALTY_MAKEUP_ARTISTS = "SPECIALTY MAKEUP ARTISTS"
    CLIENT_TESTIMONIALS = "CLIENT TESTIMONIALS"
    BRAND_PARTNERS = "BRAND PARTNERS"
